package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// Config represents the full installation configuration
type Config struct {
	// Deployment settings
	DeploymentMode string `json:"deployment_mode"` // "tailscale", "local", "native-tailscale", "terminal-only"

	// Component selection
	Components ComponentSelection `json:"components"`

	// Credentials and secrets
	Credentials Credentials `json:"credentials"`

	// Environment settings
	Environment Environment `json:"environment"`

	// Advanced options
	Advanced Advanced `json:"advanced"`
}

// ComponentSelection tracks which components to install
type ComponentSelection struct {
	Docker          bool `json:"docker"`
	Tailscale       bool `json:"tailscale"`
	TerminalTools   bool `json:"terminal_tools"`
	SSHHardening    bool `json:"ssh_hardening"`
	SecretsManager  bool `json:"secrets_manager"`
}

// Credentials holds sensitive configuration
type Credentials struct {
	TailscaleKey   string `json:"tailscale_key,omitempty"`
	CodePassword   string `json:"code_password"`
	SudoPassword   string `json:"sudo_password"`
	AnthropicKey   string `json:"anthropic_key,omitempty"`
}

// Environment holds environment-specific settings
type Environment struct {
	PUID          string `json:"puid"`
	PGID          string `json:"pgid"`
	Timezone      string `json:"timezone"`
	WorkspacePath string `json:"workspace_path"`
}

// Advanced holds advanced configuration options
type Advanced struct {
	CodeServerPort    int    `json:"code_server_port"`
	ClaudeAutomation  string `json:"claude_automation"`
	TSAcceptDNS       bool   `json:"ts_accept_dns"`
	TSExtraArgs       string `json:"ts_extra_args,omitempty"`
	TargetArch        string `json:"target_arch"`
}

// NewDefaultConfig creates a configuration with sensible defaults
func NewDefaultConfig() *Config {
	return &Config{
		DeploymentMode: "tailscale",
		Components: ComponentSelection{
			Docker:         true,
			Tailscale:      true,
			TerminalTools:  true,
			SSHHardening:   true,
			SecretsManager: true,
		},
		Credentials: Credentials{},
		Environment: Environment{
			PUID:          "1000",
			PGID:          "1000",
			Timezone:      "Europe/Berlin",
			WorkspacePath: "./workspace",
		},
		Advanced: Advanced{
			CodeServerPort:   8443,
			ClaudeAutomation: "--dangerously-skip-permissions",
			TSAcceptDNS:      false,
			TargetArch:       runtime.GOARCH,
		},
	}
}

// LoadFromFile loads configuration from a JSON file
func LoadFromFile(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file: %w", err)
	}

	config := NewDefaultConfig()
	if err := json.Unmarshal(data, config); err != nil {
		return nil, fmt.Errorf("failed to parse config file: %w", err)
	}

	return config, nil
}

// SaveToFile saves the configuration to a JSON file
func (c *Config) SaveToFile(path string) error {
	data, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to serialize config: %w", err)
	}

	if err := os.WriteFile(path, data, 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// GenerateEnvFile generates the .env file content
func (c *Config) GenerateEnvFile() string {
	var sb strings.Builder

	sb.WriteString("# Doom Coding Environment Configuration\n")
	sb.WriteString("# Generated by doom-tui\n")
	sb.WriteString(fmt.Sprintf("# Deployment mode: %s\n\n", c.DeploymentMode))

	// Tailscale Authentication
	sb.WriteString("# ===========================================\n")
	sb.WriteString("# Tailscale Authentication\n")
	sb.WriteString("# ===========================================\n")
	if c.Credentials.TailscaleKey != "" {
		sb.WriteString(fmt.Sprintf("TS_AUTHKEY=%s\n", c.Credentials.TailscaleKey))
	} else {
		sb.WriteString("# TS_AUTHKEY=tskey-auth-xxxxxxxxxxxxxxxxxxxxx\n")
	}
	sb.WriteString("\n")

	// code-server Configuration
	sb.WriteString("# ===========================================\n")
	sb.WriteString("# code-server Configuration\n")
	sb.WriteString("# ===========================================\n")
	sb.WriteString(fmt.Sprintf("CODE_SERVER_PASSWORD=%s\n", c.Credentials.CodePassword))
	sb.WriteString(fmt.Sprintf("SUDO_PASSWORD=%s\n", c.Credentials.SudoPassword))
	sb.WriteString(fmt.Sprintf("CODE_SERVER_PORT=%d\n", c.Advanced.CodeServerPort))
	sb.WriteString("\n")

	// User Settings
	sb.WriteString("# ===========================================\n")
	sb.WriteString("# User Settings\n")
	sb.WriteString("# ===========================================\n")
	sb.WriteString(fmt.Sprintf("PUID=%s\n", c.Environment.PUID))
	sb.WriteString(fmt.Sprintf("PGID=%s\n", c.Environment.PGID))
	sb.WriteString(fmt.Sprintf("TZ=%s\n", c.Environment.Timezone))
	sb.WriteString("\n")

	// Paths
	sb.WriteString("# ===========================================\n")
	sb.WriteString("# Paths\n")
	sb.WriteString("# ===========================================\n")
	sb.WriteString(fmt.Sprintf("WORKSPACE_PATH=%s\n", c.Environment.WorkspacePath))
	sb.WriteString("\n")

	// Architecture
	sb.WriteString("# ===========================================\n")
	sb.WriteString("# Architecture (auto-detected)\n")
	sb.WriteString("# ===========================================\n")
	sb.WriteString(fmt.Sprintf("TARGETARCH=%s\n", c.Advanced.TargetArch))
	sb.WriteString("\n")

	// Tailscale Options
	sb.WriteString("# ===========================================\n")
	sb.WriteString("# Tailscale Options\n")
	sb.WriteString("# ===========================================\n")
	sb.WriteString(fmt.Sprintf("TS_ACCEPT_DNS=%t\n", c.Advanced.TSAcceptDNS))
	if c.Advanced.TSExtraArgs != "" {
		sb.WriteString(fmt.Sprintf("TS_EXTRA_ARGS=%s\n", c.Advanced.TSExtraArgs))
	} else {
		sb.WriteString("# TS_EXTRA_ARGS=--advertise-tags=tag:doom-coding\n")
	}
	sb.WriteString("\n")

	// Advanced
	sb.WriteString("# ===========================================\n")
	sb.WriteString("# Advanced Settings\n")
	sb.WriteString("# ===========================================\n")
	sb.WriteString(fmt.Sprintf("CLAUDE_AUTOMATION=%s\n", c.Advanced.ClaudeAutomation))

	return sb.String()
}

// GenerateBashFlags generates the command line flags for install.sh
func (c *Config) GenerateBashFlags() []string {
	var flags []string

	flags = append(flags, "--unattended")

	if !c.Components.Docker {
		flags = append(flags, "--skip-docker")
	}
	if !c.Components.Tailscale || c.DeploymentMode == "local" {
		flags = append(flags, "--skip-tailscale")
	}
	if c.DeploymentMode == "native-tailscale" {
		flags = append(flags, "--native-tailscale")
	}
	if !c.Components.TerminalTools {
		flags = append(flags, "--skip-terminal")
	}
	if !c.Components.SSHHardening {
		flags = append(flags, "--skip-hardening")
	}
	if !c.Components.SecretsManager {
		flags = append(flags, "--skip-secrets")
	}

	if c.Credentials.TailscaleKey != "" {
		flags = append(flags, fmt.Sprintf("--tailscale-key=%s", c.Credentials.TailscaleKey))
	}
	if c.Credentials.CodePassword != "" {
		flags = append(flags, fmt.Sprintf("--code-password=%s", c.Credentials.CodePassword))
	}
	if c.Credentials.AnthropicKey != "" {
		flags = append(flags, fmt.Sprintf("--anthropic-key=%s", c.Credentials.AnthropicKey))
	}

	return flags
}

// GetComposeFile returns the appropriate docker-compose file based on deployment mode
func (c *Config) GetComposeFile() string {
	switch c.DeploymentMode {
	case "local":
		return "docker-compose.lxc.yml"
	case "native-tailscale":
		return "docker-compose.native-tailscale.yml"
	case "terminal-only":
		return ""
	default:
		return "docker-compose.yml"
	}
}

// Validate checks that the configuration is valid
func (c *Config) Validate() []string {
	var errors []string

	// Check required passwords
	if c.Components.Docker {
		if c.Credentials.CodePassword == "" {
			errors = append(errors, "code-server password is required")
		}
		if c.Credentials.SudoPassword == "" {
			errors = append(errors, "sudo password is required")
		}
	}

	// Check Tailscale key for VPN mode (not required for native-tailscale as it uses host Tailscale)
	if c.DeploymentMode == "tailscale" && c.Components.Tailscale {
		if c.Credentials.TailscaleKey == "" {
			errors = append(errors, "Tailscale auth key is required for VPN mode")
		}
	}
	// native-tailscale mode doesn't need a Tailscale key - it uses the host's Tailscale installation

	// Validate workspace path
	if c.Environment.WorkspacePath == "" {
		errors = append(errors, "workspace path cannot be empty")
	}

	return errors
}

// WriteEnvFile writes the .env file to the project directory
func (c *Config) WriteEnvFile(projectRoot string) error {
	envPath := filepath.Join(projectRoot, ".env")
	content := c.GenerateEnvFile()

	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .env file: %w", err)
	}

	return nil
}

// WriteSecretsFile creates the Anthropic API key file for Docker secrets
func (c *Config) WriteSecretsFile(projectRoot string) error {
	if c.Credentials.AnthropicKey == "" {
		return nil // No secret to write
	}

	secretsDir := filepath.Join(projectRoot, "secrets")
	if err := os.MkdirAll(secretsDir, 0700); err != nil {
		return fmt.Errorf("failed to create secrets directory: %w", err)
	}

	secretPath := filepath.Join(secretsDir, "anthropic_api_key.txt")
	if err := os.WriteFile(secretPath, []byte(c.Credentials.AnthropicKey), 0600); err != nil {
		return fmt.Errorf("failed to write API key file: %w", err)
	}

	return nil
}
